//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirConditionControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Tabel
    {
        public int DeviceAddress { get; set; }
        public string ATemp { get; set; }
        public string Aoc { get; set; }
        public string Dwind { get; set; }
        public string FModel { get; set; }
        public string HElec { get; set; }
        public string ErrorMessage { get; set; }
        public string Updatetime { get; set; }
        public string Aoctime { get; set; }
        public string eTemp { get; set; }
    }
}
